package enums;

public enum StudentRequestType {
	INQUIRY_FOR_ACADEMIC_MOBILITY, 
	INQUIRY_FOR_ONAY_CARD_RECOVERY,
	INQUIRY_FOR_MILITARY_REGISTRANTION,
	INQUIRY_FOR_DORMITORY,
	INQUIRY_TO_BE_PRESENTED_UPON_REQUEST,
	INQUIRY_FOR_RECEIVING_STATE_PENSION,
	INQUIRY_TO_GET_GAP_YEAR;
}
